CREATE TABLE IF NOT EXISTS deals(
    deal_id char(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    discount FLOAT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE (name)
)