CREATE TABLE IF NOT EXISTS permissions (
    permission_id char(36) PRIMARY KEY,
    category VARCHAR(100) UNIQUE NOT NULL,
    description TEXT DEFAULT NULL,
    permission_key VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);