CREATE TABLE IF NOT EXISTS static_pages (
    static_page_id CHAR(36) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    user_id CHAR(36) NOT NULL,
    path VARCHAR(255) NOT NULL,
    content LONGTEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
