CREATE TABLE IF NOT EXISTS bulk_products (
    id char(36) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    sku VARCHAR(100) UNIQUE NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    sub_category_id char(36) NOT NULL,
    stock_quantity INT DEFAULT 0,
    tag VARCHAR(100),
    low_stock_quantity_warning INT DEFAULT 0,
    buying_price DECIMAL(10, 2),
    weight INT,
    weight_limit INT,
    dimensions VARCHAR(100),
    age_range VARCHAR(50),
    brand VARCHAR(100),
    manufacturer VARCHAR(100),
    material TEXT,
    colors TEXT,
    sizes TEXT,
    warranty_period INT,
    created_by_id char(36) NOT NULL,
    expiry_date VARCHAR(50),
    manufacturing_date VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (sub_category_id) REFERENCES categories(category_id),
    FOREIGN KEY (created_by_id) REFERENCES users(user_id)
);