CREATE TABLE IF NOT EXISTS partners (
    partner_id CHAR(36) PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL,
    image VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);