// Package models provides data access layer for the Adenzo e-commerce platform.
//
// This file handles customer retention analytics including:
//   - Customer retention metrics (new vs returning customers)
//   - Customer order details with revenue tracking
//   - Retention trend analysis over time (monthly/quarterly/yearly)
//   - Retention rate calculations
//
// Key Concepts:
//   - New Customer: User with exactly 1 order in the period
//   - Returning Customer: User with more than 1 order in the period
//   - Retention Rate: (Returning Customers / Total Customers) * 100
package models

import (
	"fmt"
	"time"
)

// CustomerOrderDetail represents order statistics for a specific customer.
//
// This struct is used in retention reports to show individual customer
// performance within a time period.
//
// Fields:
//   - UserID: The unique user identifier
//   - OrderCount: Total number of orders placed by this customer in the period
//   - Revenue: Total revenue generated by this customer in the period
type CustomerOrderDetail struct {
	UserID     string  `json:"user_id"`
	OrderCount int64   `json:"order_count"`
	Revenue    float64 `json:"revenue"`
}

// CustomerRetention represents comprehensive customer retention analytics.
//
// This struct provides both summary metrics and detailed customer breakdowns
// for new and returning customers within a specific time period.
//
// Fields:
//   - NewCustomers: Count of customers with exactly 1 order in period
//   - ReturningCustomers: Count of customers with more than 1 order in period
//   - ReturningOrders: Total number of orders from returning customers
//   - NewOrders: Total number of orders from new customers (always equals NewCustomers)
//   - ReturningDetails: Individual customer details for returning customers (sorted by order count DESC)
//   - NewDetails: Individual customer details for new customers (sorted by revenue DESC)
type CustomerRetention struct {
	NewCustomers       int64                 `json:"new_customers"`
	ReturningCustomers int64                 `json:"returning_customers"`
	ReturningOrders    int64                 `json:"returning_orders"`
	NewOrders          int64                 `json:"new_orders"`
	ReturningDetails   []CustomerOrderDetail `json:"returning_details"`
	NewDetails         []CustomerOrderDetail `json:"new_details"`
}

// GetCustomerRetention retrieves customer retention analytics for a given time period.
//
// This function analyzes customer behavior by counting orders per user within the period.
// A customer with 1 order is considered "new", while a customer with >1 orders is "returning".
//
// Parameters:
//   - start: Start of the time period (inclusive)
//   - end: End of the time period (inclusive)
//   - months: If > 0, overrides start date by calculating end minus N months
//     (e.g., months=3 with end=2026-01-15 sets start=2025-10-15)
//
// Returns:
//   - CustomerRetention: Struct containing summary metrics and detailed customer lists
//   - error: Database error if queries fail
//
// Query Logic:
//   - Groups orders by user_id within the period
//   - Counts orders per user to determine new vs returning status
//   - ReturningDetails sorted by order_count DESC (most active first)
//   - NewDetails sorted by revenue DESC (highest value first)
func GetCustomerRetention(start, end time.Time, months int) (CustomerRetention, error) {
	// If months parameter is provided, calculate start date from end date
	if months > 0 {
		start = end.AddDate(0, -months, 0) // Go back N months from end date
	}

	// Step 1: Get summary statistics for the period
	// Uses CTE to aggregate orders per user, then categorizes as new/returning
	summaryQuery := `
		WITH user_orders AS (
			SELECT 
				o.user_id,
				COUNT(*) AS total_orders_in_period,
				SUM(o.total_amount) AS total_revenue
			FROM orders o
			WHERE o.user_id IS NOT NULL
			  AND o.last_updated_at BETWEEN ? AND ?
			GROUP BY o.user_id
		)
		SELECT
			COUNT(CASE WHEN total_orders_in_period = 1 THEN 1 END) AS new_customers,
			COUNT(CASE WHEN total_orders_in_period > 1 THEN 1 END) AS returning_customers,
			COALESCE(SUM(CASE WHEN total_orders_in_period > 1 THEN total_orders_in_period ELSE 0 END), 0) AS returning_orders,
			COALESCE(SUM(CASE WHEN total_orders_in_period = 1 THEN total_orders_in_period ELSE 0 END), 0) AS new_orders
		FROM user_orders;
	`

	var result CustomerRetention
	// Execute summary query and scan results into struct
	err := DB.QueryRow(summaryQuery, start, end).
		Scan(&result.NewCustomers, &result.ReturningCustomers, &result.ReturningOrders, &result.NewOrders)
	if err != nil {
		return CustomerRetention{}, err
	}

	// Step 2: Get detailed breakdown of returning customers
	// Users with >1 orders, sorted by order count descending
	returningQuery := `
		SELECT o.user_id, COUNT(*) AS order_count, SUM(o.total_amount) AS revenue
		FROM orders o
		WHERE o.user_id IS NOT NULL
		  AND o.last_updated_at BETWEEN ? AND ?
		GROUP BY o.user_id
		HAVING COUNT(*) > 1
		ORDER BY order_count DESC;
	`

	rows, err := DB.Query(returningQuery, start, end)
	if err != nil {
		return CustomerRetention{}, err
	}
	defer rows.Close()

	var returning []CustomerOrderDetail
	// Collect returning customer details
	for rows.Next() {
		var d CustomerOrderDetail
		if err := rows.Scan(&d.UserID, &d.OrderCount, &d.Revenue); err != nil {
			return CustomerRetention{}, err
		}
		returning = append(returning, d)
	}
	result.ReturningDetails = returning

	// Step 3: Get detailed breakdown of new customers
	// Users with exactly 1 order, sorted by revenue descending
	newQuery := `
		SELECT o.user_id, COUNT(*) AS order_count, SUM(o.total_amount) AS revenue
		FROM orders o
		WHERE o.user_id IS NOT NULL
		  AND o.last_updated_at BETWEEN ? AND ?
		GROUP BY o.user_id
		HAVING COUNT(*) = 1
		ORDER BY revenue DESC;
	`

	newRows, err := DB.Query(newQuery, start, end)
	if err != nil {
		return CustomerRetention{}, err
	}
	defer newRows.Close()

	var newDetails []CustomerOrderDetail
	// Collect new customer details
	for newRows.Next() {
		var d CustomerOrderDetail
		if err := newRows.Scan(&d.UserID, &d.OrderCount, &d.Revenue); err != nil {
			return CustomerRetention{}, err
		}
		newDetails = append(newDetails, d)
	}
	result.NewDetails = newDetails

	return result, nil
}

// CustomerRetentionTrend represents customer retention metrics for a specific time period.
//
// This struct is used for time-series retention analysis to show how customer
// retention changes over months, quarters, or years.
//
// Fields:
//   - Period: Time period identifier (format depends on groupBy: "2026-01" for month,
//     "2026-Q1" for quarter, "2026" for year)
//   - NewCustomers: Count of customers with 1 order in this period
//   - ReturningCustomers: Count of customers with >1 orders in this period
//   - RetentionRate: Percentage of returning customers (ReturningCustomers/Total*100)
type CustomerRetentionTrend struct {
	Period             string
	NewCustomers       int64
	ReturningCustomers int64
	RetentionRate      float64
}

// GetCustomerRetentionTrends retrieves customer retention trends over time periods.
//
// This function groups customer retention metrics by month, quarter, or year,
// allowing analysis of how retention changes over time.
//
// Parameters:
//   - start: Start of the time period (inclusive)
//   - end: End of the time period (inclusive)
//   - groupBy: Time grouping method - "month", "quarter", or "year"
//
// Returns:
//   - []CustomerRetentionTrend: Array of trends sorted by period ascending
//   - error: "invalid groupBy value" if groupBy is not month/quarter/year, or database error
//
// Period Formats:
//   - month: "2026-01", "2026-02", etc. (YYYY-MM)
//   - quarter: "2026-Q1", "2026-Q2", etc. (YYYY-QN)
//   - year: "2026", "2027", etc. (YYYY)
//
// Retention Rate Calculation:
//   - RetentionRate = (ReturningCustomers / (NewCustomers + ReturningCustomers)) * 100
//   - Returns 0 if no customers in period
func GetCustomerRetentionTrends(start, end time.Time, groupBy string) ([]CustomerRetentionTrend, error) {
	// Determine SQL expression for period grouping based on groupBy parameter
	var periodExpr string
	switch groupBy {
	case "month":
		periodExpr = "DATE_FORMAT(o.last_updated_at, '%Y-%m')" // e.g., "2025-09"
	case "quarter":
		periodExpr = "CONCAT(YEAR(o.last_updated_at), '-Q', QUARTER(o.last_updated_at))" // e.g., "2025-Q3"
	case "year":
		periodExpr = "YEAR(o.last_updated_at)" // e.g., "2025"
	default:
		return nil, fmt.Errorf("invalid groupBy value: %s", groupBy)
	}

	// Build dynamic query with period expression
	// Groups users by period and counts orders to determine new vs returning
	query := fmt.Sprintf(`
		WITH user_orders AS (
			SELECT 
				%s AS period,
				o.user_id,
				COUNT(*) AS total_orders
			FROM orders o
			WHERE o.user_id IS NOT NULL
			  AND o.last_updated_at BETWEEN ? AND ?
			GROUP BY period, o.user_id
		)
		SELECT 
			period,
			COUNT(CASE WHEN total_orders = 1 THEN 1 END) AS new_customers,
			COUNT(CASE WHEN total_orders > 1 THEN 1 END) AS returning_customers
		FROM user_orders
		GROUP BY period
		ORDER BY period;
	`, periodExpr)

	rows, err := DB.Query(query, start, end)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var trends []CustomerRetentionTrend
	// Iterate through periods and calculate retention rate for each
	for rows.Next() {
		var t CustomerRetentionTrend
		if err := rows.Scan(&t.Period, &t.NewCustomers, &t.ReturningCustomers); err != nil {
			return nil, err
		}

		// Calculate retention rate as percentage
		total := t.NewCustomers + t.ReturningCustomers
		if total > 0 {
			t.RetentionRate = float64(t.ReturningCustomers) / float64(total) * 100
		} else {
			// No customers in this period
			t.RetentionRate = 0
		}

		trends = append(trends, t)
	}

	return trends, nil
}

// CustomerRetentionSummary represents high-level customer retention metrics.
//
// This struct provides a simplified retention summary based on customer lifetime,
// distinguishing between customers who placed their first order in the period
// versus customers who ordered before the period.
//
// Fields:
//   - NewCustomers: Count of customers whose first order ever was in this period
//   - ReturningCustomers: Count of customers whose first order was before this period
//     but who placed orders during this period
//   - RetentionRate: Percentage of returning customers (ReturningCustomers/Total*100)
type CustomerRetentionSummary struct {
	NewCustomers       int64
	ReturningCustomers int64
	RetentionRate      float64
}

// GetCustomerRetentionSummary retrieves lifetime customer retention summary.
//
// This function differs from GetCustomerRetention by analyzing customer lifetime behavior.
// It identifies customers based on their FIRST order ever, not just orders within the period.
//
// Parameters:
//   - start: Start of the analysis period (inclusive)
//   - end: End of the analysis period (inclusive)
//
// Returns:
//   - *CustomerRetentionSummary: Pointer to summary with lifetime-based retention metrics
//   - error: Database error if query fails
//
// Customer Classification:
//   - NewCustomers: Users whose very first order (MIN(last_updated_at)) falls within [start, end]
//   - ReturningCustomers: Users whose first order was before 'start', but who placed
//     orders during [start, end]
//
// Retention Rate:
//   - RetentionRate = (ReturningCustomers / (NewCustomers + ReturningCustomers)) * 100
//   - Represents what percentage of active customers are repeat buyers
//
// Use Case:
//   - Different from GetCustomerRetention which counts orders within period
//   - This function identifies true new-to-business customers vs established customers
func GetCustomerRetentionSummary(start, end time.Time) (*CustomerRetentionSummary, error) {
	// Use CTE to find each customer's first order ever
	// Then categorize customers based on when their first order occurred
	query := `
		WITH first_orders AS (
			SELECT user_id, MIN(last_updated_at) AS first_order
			FROM orders
			GROUP BY user_id
		)
		SELECT 
			-- New customers: first order was in the period [start, end]
			COUNT(DISTINCT CASE WHEN fo.first_order BETWEEN ? AND ? THEN o.user_id END) AS new_customers,
			-- Returning customers: first order was before start, but ordered during [start, end]
			COUNT(DISTINCT CASE WHEN fo.first_order < ? AND o.last_updated_at BETWEEN ? AND ? THEN o.user_id END) AS returning_customers
		FROM orders o
		JOIN first_orders fo ON fo.user_id = o.user_id
		WHERE o.last_updated_at BETWEEN ? AND ?;
	`

	// Execute query with date parameters
	// Parameters: start, end (new customers), start, start, end (returning), start, end (WHERE filter)
	row := DB.QueryRow(query,
		start, end, // New customers check
		start, start, end, // Returning customers check
		start, end, // Overall WHERE filter
	)

	var summary CustomerRetentionSummary
	if err := row.Scan(&summary.NewCustomers, &summary.ReturningCustomers); err != nil {
		return nil, err
	}

	// Calculate retention rate as percentage of total customers
	total := summary.NewCustomers + summary.ReturningCustomers
	if total > 0 {
		summary.RetentionRate = float64(summary.ReturningCustomers) / float64(total) * 100
	}

	return &summary, nil
}
